/** Mirror of src/lib/rag/corpus.ts for Cloud Functions ingest. Keep in sync. */
export const TRANSIT_KNOWLEDGE_CORPUS = [
  {
    id: 'lrt3-overview',
    text: 'LRT3 Shah Alam Line opened 29 June 2026. It runs 37.8 km from Bandar Utama to Johan Setia with 20 stations serving Petaling Jaya, Shah Alam, and Klang. It is the main east-west rail corridor to reduce Federal Highway traffic.',
    category: 'lrt3',
    locale: 'all',
    line: 'LRT3',
    tags: ['lrt3', 'shah alam', 'johan setia', 'bandar utama', 'western corridor'],
    source: 'RapidKL / Malay Mail launch coverage',
    updatedAt: '2026-06-29',
  },
  {
    id: 'lrt3-interchanges',
    text: 'LRT3 key interchanges: Bandar Utama connects to MRT Kajang Line (PY) for TRX, Bukit Bintang, and Kajang. Glenmarie 2 connects to LRT Kelana Jaya Line for KLCC, Gombak, Putra Heights, and Subang Jaya. Jambatan Kota has a walking link to KTM Komuter Klang.',
    category: 'interchange',
    locale: 'all',
    line: 'LRT3',
    tags: ['glenmarie', 'bandar utama', 'interchange', 'ktm', 'kelana jaya', 'kajang'],
    source: 'RapidKL network map',
    updatedAt: '2026-06-29',
  },
  {
    id: 'lrt3-infill',
    text: 'Five LRT3 infill stations — Tropicana, Temasya, Raja Muda, Bukit Raja Selatan, and Bandar Botanik — are scheduled around 2028. Trains pass through without stopping until they open.',
    category: 'lrt3',
    locale: 'all',
    line: 'LRT3',
    tags: ['infill', 'future stations'],
    source: 'Budget 2024 / MyRapid',
    updatedAt: '2026-06-01',
  },
  {
    id: 'kj-line-crowd',
    text: 'LRT Kelana Jaya Line (KJL) is the busiest LRT in Klang Valley. Peak crowding is highest 7:30–9:00 and 17:30–19:30. Use coach-load hints and consider boarding at earlier stations like Gombak or Kelana Jaya instead of KLCC during peak.',
    category: 'crowd',
    locale: 'all',
    line: 'KJL',
    tags: ['crowd', 'kelana jaya', 'peak hour'],
    source: 'Beat KL traffic crowd model',
    updatedAt: '2026-01-01',
  },
  {
    id: 'py-line-reliability',
    text: 'MRT Putrajaya Line (PY) generally has high reliability. Best for cross-valley trips via TRX and Bandar Utama interchange to LRT3. Avoid driving on LDP when PY + LRT3 combo is faster.',
    category: 'line',
    locale: 'all',
    line: 'PY',
    tags: ['putrajaya', 'mrt', 'reliability', 'trx'],
    source: 'MRT Corp',
    updatedAt: '2026-01-01',
  },
  {
    id: 'ampang-delay-mode',
    text: 'LRT Ampang and Sri Petaling lines share track sections. During delays, RapidKL may run split services. Use bus bridges from Cheras or Chan Sow Lin. Beat KL traffic Delay Survival Mode suggests alternate LRT + bus combos.',
    category: 'delay',
    locale: 'all',
    line: 'AG',
    tags: ['ampang', 'sri petaling', 'delay', 'bus bridge'],
    source: 'RapidKL alerts',
    updatedAt: '2026-01-01',
  },
  {
    id: 'ktm-seat-finder',
    text: 'KTM Komuter seat availability is highest on off-peak trains (10:00–16:00). Port Klang and Batu Caves branches converge at KL Sentral. For Shah Alam corridor, transfer via KTM Klang with LRT3 at Jambatan Kota walk.',
    category: 'line',
    locale: 'all',
    line: 'KTM',
    tags: ['komuter', 'seats', 'port klang', 'kl sentral'],
    source: 'KTMB',
    updatedAt: '2026-01-01',
  },
  {
    id: 'fare-touchngo',
    text: 'RapidKL integrated fares use distance-based Touch n Go / MyRapid card pricing. Cash fares are higher. LRT3 cashless fares start around RM4.30 for short hops. Free rides on LRT3 were offered for the first month after launch.',
    category: 'fare',
    locale: 'all',
    tags: ['fare', 'touch n go', 'myrapid', 'lrt3'],
    source: 'MyRapid fare table',
    updatedAt: '2026-06-29',
  },
  {
    id: 'kl-sentral-hub',
    text: 'KL Sentral is the main multimodal hub: Kelana Jaya LRT, KTM Komuter, KLIA Ekspres/Transit, and Monorail via Nu Sentral walk. During road jams on NPE and Federal Highway, KL Sentral + rail is often faster than driving to KL city.',
    category: 'station',
    locale: 'all',
    station: 'KJ16',
    tags: ['kl sentral', 'hub', 'interchange'],
    source: 'OpenStreetMap / GTFS',
    updatedAt: '2026-01-01',
  },
  {
    id: 'jam-strategy-pj-klang',
    text: 'To beat PJ–Klang jams: use LRT3 from Bandar Utama or Glenmarie 2 instead of LDP or Federal Highway. Morning peak Federal Highway eastbound is worst 7:00–9:30. Evening westbound worst 17:30–20:00.',
    category: 'faq',
    locale: 'all',
    tags: ['jam', 'federal highway', 'ldp', 'pj', 'klang', 'strategy'],
    source: 'Beat KL traffic mission playbook',
    updatedAt: '2026-06-29',
  },
  {
    id: 'ms-lrt3-ringkas',
    text: 'Laluan LRT3 Shah Alam beroperasi 37.8 km dari Bandar Utama ke Johan Setia dengan 20 stesen. Ia mengurangkan kesesakan Lebuhraya Persekutuan. Pertukaran utama di Bandar Utama (MRT Kajang) dan Glenmarie 2 (LRT Kelana Jaya).',
    category: 'lrt3',
    locale: 'ms',
    line: 'LRT3',
    tags: ['lrt3', 'shah alam', 'kesesakan'],
    source: 'RapidKL',
    updatedAt: '2026-06-29',
  },
  {
    id: 'zh-lrt3-overview',
    text: 'LRT3 莎阿南线于 2026 年 6 月 29 日开通，全长 37.8 公里，20 个车站，连接 Bandar Utama 与 Johan Setia，缓解联邦大道车辆拥堵。主要换乘：Bandar Utama（加影线）、Glenmarie 2（格拉那再也线）。',
    category: 'lrt3',
    locale: 'zh',
    line: 'LRT3',
    tags: ['lrt3', '莎阿南', '拥堵', '换乘'],
    source: 'RapidKL',
    updatedAt: '2026-06-29',
  },
  {
    id: 'zh-kv-jam',
    text: '缓解巴生谷车辆拥堵策略：早高峰 7:00–9:30 联邦大道东向最严重，晚高峰 17:30–20:00 西向最严重。优先选择 LRT3 + MRT/LRT 换乘，而非驾车走 LDP 或联邦大道。',
    category: 'faq',
    locale: 'zh',
    tags: ['巴生谷', '车辆拥堵', '策略'],
    source: 'Beat KL traffic',
    updatedAt: '2026-06-29',
  },
  {
    id: 'offline-routing',
    text: 'Beat KL traffic caches 45,000 POIs and GTFS route fragments for offline use in Klang Valley dead zones (tunnels, basement malls). Syncs when connectivity returns.',
    category: 'faq',
    locale: 'all',
    tags: ['offline', 'gtfs', 'cache'],
    source: 'Beat KL traffic architecture',
    updatedAt: '2026-01-01',
  },
  {
    id: 'monorail-tourist',
    text: 'KL Monorail is best for short hops around Bukit Bintang, Imbi, and Raja Chulan. Connects to KL Sentral via Nu Sentral. Not ideal for long commutes during rain when roads jam — use Kelana Jaya or MRT instead.',
    category: 'line',
    locale: 'all',
    line: 'MR',
    tags: ['monorail', 'bukit bintang', 'tourist'],
    source: 'RapidKL',
    updatedAt: '2026-01-01',
  },
]
